"use client";

import { useState, useCallback } from "react";
import { Database, Lightbulb, Bot, Repeat } from "lucide-react";

const pipelineSteps = [
  {
    id: "connect",
    title: "Connect Your Data",
    description:
      "Connect to the systems where your business data lives, including warehouses, applications, and internal tools.",
    icon: Database,
  },
  {
    id: "intent",
    title: "Intent",
    description:
      "Inputs that guide how an agent should think about a problem and respond to questions. Intents are the information provided during agent creation that help shape how the agent operates. They can include table metadata, documentation, business contexts, common questions, or default instructions. Because intents are flexible and unstructured, builders can combine multiple types of inputs to guide how the agent interprets requests and generates answers.",
    icon: Lightbulb,
  },
  {
    id: "agents",
    title: "Agents",
    description:
      "AI agents that execute analytical workflows using your data, business context, and playbooks. Cimba agents combine domain knowledge, such as metric definitions, operational rules, and terminology, with structured, multi-step workflows to answer questions and perform analysis. They can investigate issues, generate insights, and run on-the-fly or pre-defined analyses while remaining governed and context-aware. Because agents are grounded in how your business actually operates, teams can rely on them to produce consistent and repeatable results.",
    icon: Bot,
  },
  {
    id: "workflows",
    title: "Workflows",
    description:
      "Step-by-step analytical processes generated by the agent to resolve a request. When an agent receives a question, it generates a workflow to carry out the required analysis. These workflows break complex problems into sequential steps that can query data, perform calculations, and produce outputs. The result is a transparent process that shows how the agent arrived at its answer.",
    icon: Repeat,
  },
];

function ImagePlaceholderSmall({ label }: { label: string }) {
  return (
    <div className="w-full aspect-video max-h-[200px] rounded-xl bg-gradient-to-br from-grey-100 to-grey-50 border border-grey-200 flex items-center justify-center flex-shrink-0">
      <span className="text-[12px] font-medium text-grey-400">{label}</span>
    </div>
  );
}

export default function HowItWorksPipeline() {
  const [selectedIndex, setSelectedIndex] = useState(0);

  const goTo = useCallback((index: number) => {
    setSelectedIndex(index);
  }, []);

  const step = pipelineSteps[selectedIndex];

  return (
    <section className="bg-grey-50 py-16 lg:py-20">
      <div className="max-w-[1280px] mx-auto px-6 lg:px-8">
        <p className="text-[16px] font-semibold text-primary uppercase tracking-[0.15em] mb-3">
          How It Works
        </p>
        <h2 className="text-2xl sm:text-3xl font-normal text-grey-900 leading-tight mb-2">
          From data to decisions
        </h2>
        <p className="text-[16px] text-grey-600 leading-relaxed max-w-2xl mb-10">
          Connect your data, add business context, build agents and playbooks,
          then run workflows that deliver governed, repeatable intelligence.
        </p>

        {/* Pipeline tabs */}
        <div className="flex flex-wrap justify-center items-stretch gap-0 mb-10 overflow-x-auto pb-2">
          {pipelineSteps.map((s, i) => (
            <button
              key={s.id}
              type="button"
              onClick={() => goTo(i)}
              className={`flex-none w-[150px] flex items-center justify-center py-3 text-center transition-colors min-w-0 ${
                i === selectedIndex
                  ? "bg-black text-white font-bold border border-black"
                  : "bg-white text-primary border border-grey-200 hover:bg-grey-50"
              }`}
            >
              <span className="text-[12px] font-semibold uppercase tracking-wide truncate">
                {s.id === "connect" ? "CONNECT" : s.title}
              </span>
            </button>
          ))}
        </div>

        {/* Card — title, hero image, description */}
        <div
          className="bg-white border border-grey-200 rounded-2xl overflow-hidden shadow-sm"
        >
          <div className="flex flex-col lg:flex-row gap-8 p-8 sm:p-10 lg:p-12">
            <div className="lg:w-2/5 flex-shrink-0">
              <ImagePlaceholderSmall
                label={step.title}
              />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-3 mb-4">
                <div
                  className={`w-10 h-10 rounded-xl flex items-center justify-center ${
                    selectedIndex === 0
                      ? "bg-primary/10 text-primary"
                      : "bg-grey-100 text-grey-700"
                  }`}
                >
                  <step.icon size={20} />
                </div>
                <h3 className="text-xl font-normal text-grey-900 leading-tight">
                  {step.title}
                </h3>
              </div>
              <p className="text-[16px] text-grey-700 leading-relaxed">
                {step.description}
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
