"use client";

import { useState, useCallback } from "react";
import Image from "next/image";

const pipelineSteps = [
  {
    id: "connect",
    title: "Connect Your Data",
    description:
      "Connect to the systems where your business data lives, including databases, data warehouses, knowledge sources (like Glean), Google Drive, applications, and internal tools.",
    imageSrc: "/how-it-works/connect.png",
  },
  {
    id: "intent",
    title: "Intent",
    description:
      "Inputs that guide how an agent should think about a problem and respond to questions. Intents are the information provided during agent creation that help shape how the agent operates. They can include table metadata, documentation, business contexts, common questions, or default instructions. Because intents are flexible and unstructured, builders can combine multiple types of inputs to guide how the agent interprets requests and generates answers.",
    imageSrc: "/how-it-works/intent.png",
  },
  {
    id: "agents",
    title: "Agents",
    description:
      "Cimba agents combine data sources, business context, and analytical logic to answer questions and perform structured analysis. They can investigate issues, generate insights, and run on-the-fly or pre-defined workflows while remaining context-aware and governed. Because agents operate within workflows and controls, teams can rely on them to produce consistent and repeatable results.",
    imageSrc: "/how-it-works/agents.png",
  },
  {
    id: "workflows",
    title: "Workflows",
    description:
      "Step-by-step analytical processes generated by the agent to resolve a request. When an agent receives a question, it generates a workflow to carry out the required analysis. These workflows break complex problems into sequential steps that can query data, perform calculations, and produce outputs. The result is a transparent process that shows how the agent arrived at its answer.",
    imageSrc: "/how-it-works/workflows.png",
  },
];

export default function HowItWorksPipeline() {
  const [selectedIndex, setSelectedIndex] = useState(0);

  const goTo = useCallback((index: number) => {
    setSelectedIndex(index);
  }, []);

  const goPrev = useCallback(() => {
    setSelectedIndex((prev) =>
      prev === 0 ? pipelineSteps.length - 1 : prev - 1
    );
  }, []);

  const goNext = useCallback(() => {
    setSelectedIndex((prev) =>
      prev === pipelineSteps.length - 1 ? 0 : prev + 1
    );
  }, []);

  const step = pipelineSteps[selectedIndex];

  return (
    <section
      id="how-it-works"
      className="bg-grey-50 py-16 lg:py-20 scroll-mt-24"
    >
      <div className="max-w-[1280px] mx-auto px-6 lg:px-8">
        <p className="text-[16px] font-semibold text-primary uppercase tracking-[0.15em] mb-3">
          How It Works
        </p>
        <h2 className="text-2xl sm:text-3xl font-normal text-grey-900 leading-tight mb-2">
          From data to decisions
        </h2>
        <p className="text-[16px] text-grey-600 leading-relaxed max-w-2xl mb-10">
          Connect your data, add business context, build agents and playbooks,
          then run workflows that deliver governed, repeatable intelligence.
        </p>

        {/* Pipeline tabs */}
        <div className="mb-10">
          {/* Mobile: stacked rounded rectangles */}
          <div className="flex flex-col gap-3 sm:hidden">
            {pipelineSteps.map((s, i) => (
              <button
                key={s.id}
                type="button"
                onClick={() => goTo(i)}
                className={`w-full flex items-center justify-center py-3 text-center transition-colors min-w-0 border rounded-xl ${
                  i === selectedIndex
                    ? "bg-primary text-white font-bold border-primary"
                    : "bg-white text-primary hover:bg-grey-50 border-grey-200"
                }`}
              >
                <span className="text-[12px] font-semibold uppercase tracking-wide truncate">
                  {s.id === "connect" ? "CONNECT" : s.title}
                </span>
              </button>
            ))}
          </div>

          {/* Desktop: single segmented pill with rounded ends */}
          <div className="hidden sm:flex justify-center">
            <div className="inline-flex flex-shrink-0 rounded-full overflow-hidden border border-grey-200 divide-x divide-grey-200">
              {pipelineSteps.map((s, i) => (
                <button
                  key={s.id}
                  type="button"
                  onClick={() => goTo(i)}
                  className={`flex-none w-[150px] flex items-center justify-center py-3 text-center transition-colors min-w-0 border-0 ${
                    i === selectedIndex
                      ? "bg-primary text-white font-bold"
                      : "bg-white text-primary hover:bg-grey-50"
                  }`}
                >
                  <span className="text-[12px] font-semibold uppercase tracking-wide truncate">
                    {s.id === "connect" ? "CONNECT" : s.title}
                  </span>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Card — title, hero image, description */}
        <div
          className="bg-white border border-grey-200 rounded-2xl overflow-hidden shadow-sm"
        >
          <div className="flex flex-col lg:flex-row h-auto lg:h-[270px]">
            <div className="w-full lg:w-[600px] lg:h-[270px] flex-shrink-0 border-b lg:border-b-0 lg:border-r border-grey-200 overflow-hidden bg-white">
              <Image
                src={step.imageSrc}
                alt={step.title}
                width={600}
                height={270}
                className="block w-full h-auto lg:h-full object-cover"
                unoptimized
              />
            </div>
            <div className="min-w-0 flex flex-col justify-center p-8 sm:p-10 lg:p-12">
              <div className="mb-4">
                <h3 className="text-2xl font-normal text-grey-900 leading-tight">
                  {step.title}
                </h3>
              </div>
              <p className="text-[16px] text-grey-700 leading-relaxed">
                {step.description}
                {step.id === "connect" && (
                  <>
                    {" "}
                    <a
                      href="#integrations"
                      className="underline underline-offset-2 hover:text-primary transition-colors"
                    >
                      View All
                    </a>
                  </>
                )}
              </p>
              <div className="mt-6 flex items-center justify-between sm:hidden">
                <button
                  type="button"
                  onClick={goPrev}
                  aria-label="Previous step"
                  className="inline-flex items-center justify-center rounded-lg border border-grey-200/80 bg-white px-3 py-2 text-[12px] font-semibold uppercase tracking-wide text-primary/70 transition-colors hover:bg-grey-50/60"
                >
                  Prev
                </button>
                <div className="flex items-center gap-2">
                  {pipelineSteps.map((s, i) => (
                    <button
                      key={s.id}
                      type="button"
                      onClick={() => goTo(i)}
                      aria-label={`Go to ${s.title}`}
                      aria-current={i === selectedIndex ? "step" : undefined}
                      className={`h-2.5 rounded-full transition-all ${
                        i === selectedIndex
                          ? "w-6 bg-primary"
                          : "w-2.5 bg-grey-300 hover:bg-grey-400"
                      }`}
                    />
                  ))}
                </div>
                <button
                  type="button"
                  onClick={goNext}
                  aria-label="Next step"
                  className="inline-flex items-center justify-center rounded-lg border border-grey-200/80 bg-white px-3 py-2 text-[12px] font-semibold uppercase tracking-wide text-primary/70 transition-colors hover:bg-grey-50/60"
                >
                  Next
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
