"use client";

import { useState, useEffect, useCallback } from "react";
import {
  Database,
  Lightbulb,
  Bot,
  BrainCircuit,
  BookOpen,
  Server,
  Repeat,
  Mail,
  Key,
  Share2,
  ShieldCheck,
  BarChart3,
} from "lucide-react";
const ROTATE_INTERVAL_MS = 6000;

const pipelineSteps = [
  {
    id: "connect",
    title: "Connect Your Data",
    description:
      "Connect to the systems where your business data lives, including warehouses, applications, and internal tools.",
    icon: Database,
  },
  {
    id: "intent",
    title: "Intent",
    description:
      "Inputs that guide how an agent should think about a problem and respond to questions. Intents are the information provided during agent creation that help shape how the agent operates. They can include table metadata, documentation, business contexts, common questions, or default instructions. Because intents are flexible and unstructured, builders can combine multiple types of inputs to guide how the agent interprets requests and generates answers.",
    icon: Lightbulb,
  },
  {
    id: "agents",
    title: "Agents",
    description:
      "AI agents that execute analytical workflows using your data and business context. Cimba agents combine data sources, business context, and analytical logic to answer questions and perform structured analysis. They can investigate issues, generate insights, and run on-the-fly or pre-defined workflows while remaining context-aware and governed. Because agents operate within workflows and controls, teams can rely on them to produce consistent and repeatable results.",
    icon: Bot,
  },
  {
    id: "business-context",
    title: "Business Context",
    description:
      "Domain knowledge that teaches the agent how your organization defines metrics, terms, and business logic. Business context allows teams to encode the meaning behind their data so agents interpret questions correctly. This can include definitions of key metrics, operational rules, and terminology used across the organization. By grounding agents in this context, Cimba ensures that insights reflect how the business actually operates.",
    icon: BrainCircuit,
  },
  {
    id: "playbooks",
    title: "Playbooks",
    description:
      "Pre-defined workflows on how complex analyses should run. Playbooks are like a recipe that break down analytical tasks into multi-step processes that guide how questions are answered. They transform complex analysis into repeatable workflows that teams can run consistently across the organization. Built-in validation helps ensure each step is clear, complete, and reliable before the workflow is executed.",
    icon: BookOpen,
  },
  {
    id: "mcp",
    title: "MCP Server",
    description:
      "Interoperability allows external agents and tools to interact with Cimba. Cimba provides an MCP server that exposes agents, workflows, and data connections through a structured interface. This allows external AI systems and tools to discover, control, and integrate with Cimba workflows. As a result, organizations can connect Cimba into broader AI ecosystems and automate workflows across multiple systems.",
    icon: Server,
  },
  {
    id: "workflows",
    title: "Workflows",
    description:
      "Step-by-step analytical processes generated by the agent to resolve a request. When an agent receives a question or executes a playbook, it generates a workflow to carry out the required analysis. These workflows break complex problems into sequential steps that can query data, perform calculations, and produce outputs. The result is a transparent process that shows how the agent arrived at its answer.",
    icon: Repeat,
  },
  {
    id: "platform",
    title: "Platform Capabilities",
    isCapabilities: true,
    capabilities: [
      { icon: Mail, label: "SMTP / enterprise email support" },
      { icon: Key, label: "SCIM and LDAP" },
      { icon: Share2, label: "Sharing and access control" },
      { icon: ShieldCheck, label: "Governed access & context control" },
      { icon: BarChart3, label: "Charts in summaries" },
    ],
    icon: ShieldCheck,
  },
];

function ImagePlaceholderSmall({ label }: { label: string }) {
  return (
    <div className="w-full aspect-video max-h-[200px] rounded-xl bg-gradient-to-br from-grey-100 to-grey-50 border border-grey-200 flex items-center justify-center flex-shrink-0">
      <span className="text-[12px] font-medium text-grey-400">{label}</span>
    </div>
  );
}

export default function HowItWorksPipeline() {
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [paused, setPaused] = useState(false);

  const goTo = useCallback((index: number) => {
    setSelectedIndex(index);
    setPaused(true);
    setTimeout(() => setPaused(false), 4000);
  }, []);

  useEffect(() => {
    if (paused) return;
    const t = setInterval(() => {
      setSelectedIndex((i) => (i + 1) % pipelineSteps.length);
    }, ROTATE_INTERVAL_MS);
    return () => clearInterval(t);
  }, [paused]);

  const step = pipelineSteps[selectedIndex];
  const isCapabilities = "isCapabilities" in step && step.isCapabilities;

  return (
    <section className="bg-grey-50 py-20 lg:py-28">
      <div className="max-w-[1280px] mx-auto px-6 lg:px-8">
        <p className="text-[13px] font-semibold text-primary uppercase tracking-[0.15em] mb-3">
          How It Works
        </p>
        <h2 className="text-2xl sm:text-3xl font-bold text-grey-900 leading-tight mb-2">
          From data to decisions
        </h2>
        <p className="text-[15px] text-grey-600 leading-relaxed max-w-2xl mb-10">
          Connect your data, add business context, build agents and playbooks,
          then run workflows that deliver governed, repeatable intelligence.
        </p>

        {/* Pipeline tabs — arrow-shaped, left to right */}
        <div className="flex flex-wrap items-stretch gap-0 mb-10 overflow-x-auto pb-2">
          {pipelineSteps.map((s, i) => (
            <button
              key={s.id}
              type="button"
              onClick={() => goTo(i)}
              className={`flex items-center gap-2 pl-4 pr-6 py-3 text-left transition-colors min-w-0 max-w-[180px] sm:max-w-none ${
                i === selectedIndex
                  ? "bg-black text-white font-bold"
                  : "bg-white text-primary border border-grey-200 hover:bg-grey-50"
              }`}
              style={{
                clipPath:
                  "polygon(0 0, calc(100% - 10px) 0, 100% 50%, calc(100% - 10px) 100%, 0 100%)",
                marginLeft: i > 0 ? -10 : 0,
                zIndex: i === selectedIndex ? 10 : 1,
              }}
            >
              <span className="text-[12px] font-semibold uppercase tracking-wide truncate">
                {s.title}
              </span>
            </button>
          ))}
        </div>

        {/* Card — title, hero image, description */}
        <div
          className="bg-white border border-grey-200 rounded-2xl overflow-hidden shadow-sm"
          onMouseEnter={() => setPaused(true)}
          onMouseLeave={() => setPaused(false)}
        >
          <div className="flex flex-col lg:flex-row gap-8 p-8 sm:p-10 lg:p-12">
            <div className="lg:w-2/5 flex-shrink-0">
              <ImagePlaceholderSmall
                label={isCapabilities ? "Platform" : step.title}
              />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-3 mb-4">
                <div
                  className={`w-10 h-10 rounded-xl flex items-center justify-center ${
                    selectedIndex === 0
                      ? "bg-primary/10 text-primary"
                      : "bg-grey-100 text-grey-700"
                  }`}
                >
                  <step.icon size={20} />
                </div>
                <h3 className="text-xl font-bold text-grey-900 leading-tight">
                  {step.title}
                </h3>
              </div>
              {isCapabilities && "capabilities" in step ? (
                <div className="flex flex-wrap gap-3">
                  {step.capabilities.map((cap) => (
                    <span
                      key={cap.label}
                      className="inline-flex items-center gap-2 px-4 py-2 bg-grey-100 border border-grey-200 rounded-full text-[13px] font-medium text-grey-700"
                    >
                      <cap.icon size={14} className="text-primary" />
                      {cap.label}
                    </span>
                  ))}
                </div>
              ) : (
                <p className="text-[15px] text-grey-700 leading-relaxed">
                  {step.description}
                </p>
              )}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
